"""Initial migration.

Revision ID: 930d3ac35540
Revises: 3ffd3e8d8cf4
Create Date: 2024-03-20 10:34:08.891321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930d3ac35540'
down_revision = '3ffd3e8d8cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('afe', sa.String(length=50), nullable=False),
    sa.Column('process_path', sa.String(length=100), nullable=False),
    sa.Column('error', sa.String(length=100), nullable=False),
    sa.Column('durable', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    # ### end Alembic commands ###
